apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    run: mypod
spec:
  containers:
  - image: jaskirat05/new-ui:latest
    name: new-ui
    imagePullPolicy: Never
    ports:
    - containerPort: 3001
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  

